repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs

-   repo: https://github.com/doublify/pre-commit-rust
    rev: 'eeee35a'
    hooks:
    -   id: fmt

    -   id: clippy
        name: Rust clippy
        entry: bash -c 'cargo clippy --all-targets --all-features -- -Dclippy::all'
        pass_filenames: false
        types: [file, rust]
        language: system

-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 'v0.32.0'
    hooks:
    -   id: markdownlint-fix
        args: ['--fix']
