name: pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: wget https://github.com/protocolbuffers/protobuf/releases/download/v3.20.0/protoc-3.20.0-linux-x86_64.zip &&
        unzip protoc-3.20.0-linux-x86_64.zip &&
        sudo cp -r include/* /usr/local/include &&
        sudo cp bin/protoc /usr/bin/
    - uses: pre-commit/action@v3.0.0
